language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
notifications:
  email: false
script:
  - yarn run test
after_success:
  - npm install -g codecov
  - codecov
branches:
  only:
    - master
